# Generated by Django 3.1.1 on 2020-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='fname',
            field=models.CharField(default='Shruti', max_length=122),
        ),
        migrations.AddField(
            model_name='signup',
            name='lname',
            field=models.CharField(default='Bhattarai', max_length=122),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=122),
        ),
    ]
