# Generated by Django 3.1.1 on 2020-11-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201121_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='last_name',
        ),
    ]
