# Generated by Django 3.1.1 on 2020-12-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201127_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
