# Generated by Django 3.1.1 on 2020-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='picture',
            field=models.ImageField(null=True, upload_to='clothes/pictures'),
        ),
    ]
