# Generated by Django 3.1.1 on 2020-12-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_clothes_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
